# Generated by Django 4.2.6 on 2024-01-18 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 1, 18, 11, 54, 44, 704453), verbose_name='Опубликована'),
        ),
    ]
