# Generated by Django 4.2.6 on 2024-01-18 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 1, 18, 12, 1, 6, 980735), verbose_name='Опубликована'),
        ),
    ]
