# Generated by Django 4.2.6 on 2024-03-23 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blog_description_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 3, 24, 0, 2, 5, 725217), verbose_name='Опубликована'),
        ),
    ]
