# Generated by Django 4.2.6 on 2024-03-24 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_comment_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'статья блога', 'verbose_name_plural': 'статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 3, 25, 1, 0, 9, 370178), verbose_name='Опубликована'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
