# Generated by Django 4.2.6 on 2024-03-24 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_comment_options_alter_blog_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.blog', verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 3, 25, 1, 6, 3, 392387), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
