# Generated by Django 4.2.6 on 2024-03-24 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment_post1_alter_blog_posted_alter_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post1',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 3, 25, 1, 7, 2, 40323), verbose_name='Опубликована'),
        ),
    ]
