# Generated by Django 4.2.6 on 2024-05-10 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_blog_image_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'статья блога', 'verbose_name_plural': 'статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 5, 10, 15, 7, 37, 427489), verbose_name='Опубликована'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Blog',
        ),
    ]
